version: "3.8"

services:

  configserver:
    image: saipavan9594/section7-configserver2:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
     - eazybank
      
  accounts:
    image: saipavan9594/section7-accounts:latest
    mem_limit: 700m
    ports:
      - "8081:8081"
    networks:
      - eazybank
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 360s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      # in the abbove the uri mentioned as "http://configserver:8071/" --- "configserver" mentioned is the service name which is under services section at line:5
  
  loans:
    image: saipavan9594/section7-loans:latest
    mem_limit: 700m
    ports:
      - "8082:8082"
    networks:
      - eazybank
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 360s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
    
  cards:
    image: saipavan9594/section7-cards:latest
    mem_limit: 700m
    ports:
      - "8083:8083"
    networks:
      - eazybank
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 360s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      
networks:
  eazybank: